title: Dana Amundsen
description: Comic Artist and Web Witch
theme: jekyll-theme-architect
google_analytics: 
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  
collections:
  portfolio_items:
    output: true
    permalink: "/portfolio/:path/"
    title: true
    date: true
    img: true
    alt: true

body_font: Karla #font used for body text
header_font: Berkshire Swash #font used for title and header

font_color: "#241C07"
background_color: "#fff"
color1: "#241C07" #color of links and headers
color2: "#A17649" #color of links on hover

img_base_url: http://danaamundsen.site44.com
