title: Dana Amundsen  
logo: /assets/img/logo2.png
description: Comic Artist and Web Witch
google_analytics: 
remote_theme: pages-themes/dinky@v0.2.0
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  
collections:
  portfolio_items:
    output: true
    permalink: "/portfolio/:path/"
    title: true
    date: true
    img: true
    alt: true

body_font: Roboto Mono #font used for body text
header_font: VT323 #Silkscreen #font used for title and header
tiny_font: 
title_font: Monofett
background_color: "#000"
font_color: "#fff"
color1: "#fff" #color of links and headers
color2: "#ccc" #color of links on hover

img_base_url: http://danaamundsen.site44.com
