title: Dana Amundsen
description: Designer and Visual Storyteller
theme: jekyll-theme-architect
google_analytics: G-5VT7SR50E1
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  
collections:
  portfolio_items:
    output: true
    permalink: "/portfolio/:path/"
    title: true
    date: true
    img: true
    alt: true

body_font: Karla #font used for body text
header_font: Berkshire Swash #font used for title and header

font_color: "#fff"
background_color: "#19101F"
color1: "#74608F" #color of links and headers
color2: "#51485D" #color of links on hover

img_base_url: /assets/img
