title: Dana Amundsen
logo: /assets/img/logo.png
description: Artist and Web Developer
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate

body_font: Baskerville Libre #font used for body text
header_font: Rye #font used for title and header
background_color: "#fff"
font_color: "#000"
color1: "#000" #color of links and headers
color2: "#000" #color of links on hover

img_base_url: http://danaamundsen.site44.com
