title: Dana Amundsen  
logo: /assets/img/logo2.png
description: Illustrator, Comic Artist, Web Witch
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  
collections:
  portfolio_items:
    output: true
    permalink: "/portfolio/:path/"
    title: true
    date: true
    img: true
    alt: true

body_font: Karla #font used for body text
header_font: Nanum Pen Script #font used for title and header
tiny_font:
background_color: "#333"
font_color: "#fff"
color1: "#fff" #color of links and headers
color2: "#ccc" #color of links on hover

img_base_url: http://danaamundsen.site44.com
