title: Dana Amundsen
logo: /assets/img/logo.png
description: Artist and Illustrator
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate

body_font: Libre Baskerville #font used for body text
header_font: Rye #font used for title and header
background_color: "#AEA394"
font_color: "#1A1E1F"
color1: "#5A462D" #color of links and headers
color2: "#623923" #color of links on hover

img_base_url: http://danaamundsen.site44.com
